name: Sync All Spaces
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Critical for subtree history

      - name: Initialize Subtrees
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Add subtrees if missing (idempotent)
          git remote add mediagent_main https://huggingface.co/spaces/Sameer747/MediMateAIAgent || true
          git fetch mediagent_main
          git subtree add --prefix=MediMateAIAgent mediagent_main/main --squash -m "Add subtree" || true

          git remote add mediagent_women https://huggingface.co/spaces/Sameer747/MediMateAIAgentWomensHealth || true
          git fetch mediagent_women
          git subtree add --prefix=MediMateAIAgentWomensHealth mediagent_women/main --squash -m "Add subtree" || true

          git remote add mediagent_elderly https://huggingface.co/spaces/Sameer747/MediMateAIAgentElderly || true
          git fetch mediagent_elderly
          git subtree add --prefix=MediMateAIAgentElderly mediagent_elderly/main --squash -m "Add subtree" || true

          git remote add mediagent_child https://huggingface.co/spaces/Sameer747/MediMateAIAgentChildHealthAndGrowth || true
          git fetch mediagent_child
          git subtree add --prefix=MediMateAIAgentChildHealthAndGrowth mediagent_child/main --squash -m "Add subtree" || true

      - name: Sync Changes
        run: |
          # Pull updates
          git subtree pull --prefix=MediMateAIAgent https://huggingface.co/spaces/Sameer747/MediMateAIAgent main --squash
          git subtree pull --prefix=MediMateAIAgentWomensHealth https://$HF_TOKEN@huggingface.co/spaces/Sameer747/MediMateAIAgentWomensHealth main --squash
          git subtree pull --prefix=MediMateAIAgentElderly https://$HF_TOKEN@huggingface.co/spaces/Sameer747/MediMateAIAgentElderly main --squash
          git subtree pull --prefix=MediMateAIAgentChildHealthAndGrowth https://$HF_TOKEN@huggingface.co/spaces/Sameer747/MediMateAIAgentChildHealthAndGrowth main --squash

          # Push to GitHub
          git push github main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
